[[redirects]]
  from = "/*"
  to = "/cris-doces/:splat"
  status = 200
  force = true
  [redirects.conditions]
    Host = "crisdoces.siteslink.com.br"

[[redirects]]
  from = "/*"
  to = "/ulisses-informatica/:splat"
  status = 200
  force = true
  [redirects.conditions]
    Host = "ulissesinformatica.siteslink.com.br"

[[redirects]]
  from = "/*"
  to = "/sitio-mendes/:splat"
  status = 200
  force = true
  [redirects.conditions]
    Host = "sitiomendes.siteslink.com.br"

[[redirects]]
  from = "/*"
  to = "/william-automecanica/:splat"
  status = 200
  force = true
  [redirects.conditions]
    Host = "williammecanica.siteslink.com.br"
